### ISSUE TITLE
🐛 The off toggle doesn't remain off 

### ISSUE THREAD

**Issue by aaaclones** [reworkd/AgentGPT#596]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

The external options like image , web search and code are useless and they automatically toggle back on , I am not sure what the feature is here this actually hinders the process ...  It looks like agentGPT starts to ramble and hallucinates , the overfitting and cram of endless subtask .. and in the end after 30 runs the task at hand never even finishes . so in terms of average it goes 0/30 after the senseless upgrade ..... autogpt>>>>>>>>>>>

### Current behaviour

nothing happens , just continuous sub task .. and code that are meaningless

### Steps to reproduce

not sure 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by asim-shrestha** [comment]
Hi there, this may have to do with TRPC re-querying the data and inadvertently resetting the parameters.

We'll look into this for you

**Comment by aaaclones** [comment]
there are endless amount of issues , I am not sure what goal is here it's a
whole maze to try to do anything , the 30 runs did absolutely nothing but
just loop til confusion and hallucination

**Comment by aaaclones** [comment]
furthermore , the image and the code option does nothing but clutter the
user friend ui/

**Comment by awtkns** [comment]
fix in: https://github.com/reworkd/AgentGPT/commit/7836c46057fb48c9c26e2dc53b9a81e002d4c630
